Add OnePlus, fix vayu
Project-Aloha/DocumentWebsite pull request #6
Opened 2024-10-11 21:19 UTC by n00b69

Add link to OnePlus 7(T) Pro 4G guide, fix vayu link

2024-10-12 09:41 UTC, gus33000 requested changes
Given this PR was not made by any authority owned any of the vayu guide, I would lean towards the removal of the vayu link entirely, unless the owners of the existing guides manifest themselves and approve such change.

tagref:[CONFLICT/POLITICS] Sog/VayuOrg

2024-10-12 09:44 UTC, gus33000 commented
enrolling @NetuserPRO as well for the very same reasons

2024-10-12 11:36 UTC, remtrik approved these changes

2024-10-13 08:30 UTC, NetuserPRO approved these changes

2024-10-13 09:18 UTC, gus33000 approved these changes

2024-10-13 09:18 UTC, merged